/**
 * metaweather
 *
 * metaweather.com
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package one.beagile.metaweatherClient.models

import one.beagile.metaweatherClient.models.WeatherState
import one.beagile.metaweatherClient.models.WeatherStateAbbreviation

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param weatherStateName 
 * @param weatherStateAbbr 
 * @param windDirectionCompass 
 * @param created 
 * @param applicableDate 
 * @param minTemp 
 * @param maxTemp 
 * @param theTemp 
 * @param winSpeed 
 * @param winDirection 
 * @param airPressure 
 * @param humidity 
 * @param visibility 
 * @param predictability 
 */
@Serializable
data class LocationWeather (

    @SerialName(value = "id") val id: kotlin.String? = null,

    @SerialName(value = "weather_state_name") val weatherStateName: WeatherState? = null,

    @SerialName(value = "weather_state_abbr") val weatherStateAbbr: WeatherStateAbbreviation? = null,

    @SerialName(value = "wind_direction_compass") val windDirectionCompass: kotlin.String? = null,

    @SerialName(value = "created") val created: kotlin.String? = null,

    @SerialName(value = "applicable_date") val applicableDate: kotlin.String? = null,

    @SerialName(value = "min_temp") val minTemp: kotlin.Double? = null,

    @SerialName(value = "max_temp") val maxTemp: kotlin.Double? = null,

    @SerialName(value = "the_temp") val theTemp: kotlin.Double? = null,

    @SerialName(value = "win_speed") val winSpeed: kotlin.Double? = null,

    @SerialName(value = "win_Direction") val winDirection: kotlin.Double? = null,

    @SerialName(value = "air_pressure") val airPressure: kotlin.Double? = null,

    @SerialName(value = "humidity") val humidity: kotlin.Double? = null,

    @SerialName(value = "visibility") val visibility: kotlin.Double? = null,

    @SerialName(value = "predictability") val predictability: kotlin.Double? = null

)

