/**
 * metaweather
 *
 * metaweather.com
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package one.beagile.metaweatherClient.models

import one.beagile.metaweatherClient.models.LocationType

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param title 
 * @param locationType 
 * @param woeid 
 * @param lattLong 
 */
@Serializable
data class LocationParent (

    @SerialName(value = "title") val title: kotlin.String? = null,

    @SerialName(value = "location_type") val locationType: LocationType? = null,

    @SerialName(value = "woeid") val woeid: kotlin.Int? = null,

    @SerialName(value = "latt_long") val lattLong: kotlin.String? = null

)

