/**
 * metaweather
 *
 * metaweather.com
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package one.beagile.metaweatherClient.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param title 
 * @param slug 
 * @param url 
 * @param crawlRate 
 */
@Serializable
data class WeatherSource (

    @SerialName(value = "title") val title: kotlin.String? = null,

    @SerialName(value = "slug") val slug: kotlin.String? = null,

    @SerialName(value = "url") val url: kotlin.String? = null,

    @SerialName(value = "crawl_rate") val crawlRate: kotlin.Double? = null

)

