openapi: 3.0.3
info:
  title: NewsAPI
  description: NewsAPI.org
  version: 1.0.0
servers:
- url: https://newsapi.org/v2
tags:
- name: articles
  description: News articles
paths:
  /everything/:
    get:
      tags:
      - news
      summary: News List
      operationId: everythingGet
      parameters:
      - name: q
        in: query
        description: Theme of news
        required: true
        schema:
          type: string
      - name: from
        in: query
        description: date and optional time for the oldest article
        schema:
          type: string
          format: date-time
      - name: to
        in: query
        description: date and optional time for the newest article
        schema:
          type: string
          format: date-time
      - name: sortBy
        in: query
        description: Sort
        required: true
        schema:
          $ref: '#/components/schemas/ArticleSort'
      - name: language
        in: query
        description: Language in two letters
        schema:
          type: string
      - name: apiKey
        in: query
        description: API key
        required: true
        schema:
          type: string
      - name: page
        in: query
        description: number of page
        schema:
          type: integer
      - name: pageSize
        in: query
        description: number of results to return per page
        schema:
          type: integer
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArticleList'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
components:
  schemas:
    ArticleSort:
      type: string
      enum:
        - relevancy
        - popularity
        - publishedAt
    ArticleList:
      type: object
      properties:
        status:
          type: string
        totalResults:
          type: integer
        articles:
          type: array
          items:
            $ref: '#/components/schemas/Article'
    ErrorModel:
      required:
      - code
      - message
      type: object
      properties:
        status:
          type: string
        message:
          type: string
        code:
          maximum: 600
          minimum: 100
          type: integer
    Article:
      required:
      - url
      type: object
      properties:
        source:
          $ref: '#/components/schemas/Source'
        author:
          type: string
        title:
          type: string
        description:
          type: string
        url:
          type: string
        urlToImage:
          type: string
        publishedAt:
          type: string
        content:
          type: string
    Source:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
