//
// ArticleSort.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum ArticleSort: String, Codable, CaseIterable {
    case relevancy = "relevancy"
    case popularity = "popularity"
    case publishedat = "publishedAt"
}
