//
// LocationType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum LocationType: String, Codable, CaseIterable {
    case continent = "Continent"
    case country = "Country"
    case city = "City"
    case regionStateProvince = "Region / State / Province"
}
