//
// WeatherStateAbbreviation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum WeatherStateAbbreviation: String, Codable, CaseIterable {
    case sn = "sn"
    case sl = "sl"
    case h = "h"
    case t = "t"
    case hr = "hr"
    case lr = "lr"
    case s = "s"
    case hc = "hc"
    case lc = "lc"
    case c = "c"
}
