//
// Location.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct Location: Codable, Hashable {

    public var distance: Double?
    public var title: String
    public var woeid: Int
    public var locationType: String?
    public var lattLong: String

    public init(distance: Double? = nil, title: String, woeid: Int, locationType: String? = nil, lattLong: String) {
        self.distance = distance
        self.title = title
        self.woeid = woeid
        self.locationType = locationType
        self.lattLong = lattLong
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case distance
        case title
        case woeid
        case locationType = "location_type"
        case lattLong = "latt_long"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(distance, forKey: .distance)
        try container.encode(title, forKey: .title)
        try container.encode(woeid, forKey: .woeid)
        try container.encodeIfPresent(locationType, forKey: .locationType)
        try container.encode(lattLong, forKey: .lattLong)
    }



}
